[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "tailwindcss -c ./tailwind.config.js -i ./tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css --minify"]